version: 2.1
commands:
  run-rails-test:
    description: "Railsのテストを実行"
    steps:
      - run:
          command: |
            bundle exec rake db:create
            bundle exec rake db:schema:load
      - run: bundle exec rspec
jobs:
  build:
    working_directory: ~/circleci-demo-ruby-rails
    docker:
      - image: circleci/ruby:2.4.1-node
        environment:
          RAILS_ENV: test
      - image: circleci/postgres:9.4.12-alpine
    steps:
      - when:
          condition: false
          steps:
            - run: echo \"my custom checkout\"

      - checkout

      - restore_cache:
          keys:
            - v1-rails-demo-{{ checksum "Gemfile.lock" }}
            - v1-rails-demo

      - run: bundle install --path vendor/bundle

      - save_cache:
          key: v1-rails-demo-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run-rails-test
